
set(CORTEX_PLATFORM_WINDOWS 0)
set(CORTEX_PLATFORM_IOS 0)
set(CORTEX_PLATFORM_MACOS 0)
set(CORTEX_PLATFORM_LINUX 0)
set(CORTEX_PLATFORM_ANDROID 0)

if(WIN32) 
    set(CORTEX_PLATFORM_WINDOWS 1)
    message("Windows")
elseif(MINGW)
    message(FATAL_ERROR "MinGW is not supported yet.")
elseif(APPLE)
    if(IOS)
        set(CORTEX_PLATFORM_IOS 1)
        message(FATAL_ERROR "IOS is not supported yet.")
    else()
        set(CORTEX_PLATFORM_MACOS 1)
        message(FATAL_ERROR "MacOS is not supported yet")
    endif()
elseif(UNIX)
    # we dont have a linux cmake variable so this is the only option available
    if(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
        set(CORTEX_PLATFORM_LINUX 1)
        message(FATAL_ERROR "Linux is not supported yet")
    elseif(ANDROID)
        set(CORTEX_PLATFORM_ANDROID 1)
        message(FATAL_ERROR "Android is not supported yet.")
    else()
        message(FATAL_ERROR "This Unix-based operating system is not supported yet.")
    endif()
else()
    message(FATAL_ERROR "Your operating system is not supported yet.")
endif()